#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Similardio.Resource", IsApplication=true)]

namespace Similardio
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int close_btn = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int close_btn_down = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int close_btn_normal = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int lastfm_logo = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int LoadingBackground = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int question_btn = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int question_btn_down = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int question_btn_normal = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int RateBackground = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int rdio_logo = 2130837514;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050001
			public const int ArtistBgImage = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int ArtistDrawer = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int ArtistScore = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int artistImageLoading = 2131034112;
			
			// aapt resource value: 0x7f050004
			public const int artistName = 2131034116;
			
			// aapt resource value: 0x7f050008
			public const int containerFrame = 2131034120;
			
			// aapt resource value: 0x7f05000a
			public const int explText = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int extraExpl = 2131034123;
			
			// aapt resource value: 0x7f050006
			public const int libraryHeaderText = 2131034118;
			
			// aapt resource value: 0x7f050009
			public const int logoImage = 2131034121;
			
			// aapt resource value: 0x7f05000c
			public const int mainContainer = 2131034124;
			
			// aapt resource value: 0x7f050005
			public const int questionBtn = 2131034117;
			
			// aapt resource value: 0x7f05000d
			public const int similarArtistText = 2131034125;
			
			// aapt resource value: 0x7f050007
			public const int similarArtistsList = 2131034119;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ArtistItemLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int LoadingScreen = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int SimilarArtistItem = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
